//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelephoneDirectory.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsActive { get; set; }
        public int RoleId { get; set; }
        public int SupervisorId { get; set; }
        public int DepartmentId { get; set; }
        public int TitleId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Role Role { get; set; }
        public virtual Title Title { get; set; }
    }
}
