//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelephoneDirectory.UI.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string EDET_BACK_TO_LIST {
            get {
                return ResourceManager.GetString("EDET_BACK_TO_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string EDET_DETAIL {
            get {
                return ResourceManager.GetString("EDET_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EDET_EMAIL {
            get {
                return ResourceManager.GetString("EDET_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Detail.
        /// </summary>
        public static string EDET_EMPLOYEE_DETAIL {
            get {
                return ResourceManager.GetString("EDET_EMPLOYEE_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string EDET_FIRST_NAME {
            get {
                return ResourceManager.GetString("EDET_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string EDET_LAST_NAME {
            get {
                return ResourceManager.GetString("EDET_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string EDET_TELEPHONE {
            get {
                return ResourceManager.GetString("EDET_TELEPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string EMPS_EMPLOYEES {
            get {
                return ResourceManager.GetString("EMPS_EMPLOYEES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string EMPS_FIRST_NAME {
            get {
                return ResourceManager.GetString("EMPS_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string EMPS_LAST_NAME {
            get {
                return ResourceManager.GetString("EMPS_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string EMPS_TELEPHONE {
            get {
                return ResourceManager.GetString("EMPS_TELEPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string EPLST_EMPLOYEES {
            get {
                return ResourceManager.GetString("EPLST_EMPLOYEES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string EPLST_FIRST_NAME {
            get {
                return ResourceManager.GetString("EPLST_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string EPLST_LAST_NAME {
            get {
                return ResourceManager.GetString("EPLST_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string EPLST_LIST {
            get {
                return ResourceManager.GetString("EPLST_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string EPLST_TELEPHONE {
            get {
                return ResourceManager.GetString("EPLST_TELEPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Directory | Coded by Sefa DOGAN..
        /// </summary>
        public static string FTR_SIGNATURE {
            get {
                return ResourceManager.GetString("FTR_SIGNATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get More Libraries.
        /// </summary>
        public static string HOME_GET_MORE_LIBRARIES {
            get {
                return ResourceManager.GetString("HOME_GET_MORE_LIBRARIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects..
        /// </summary>
        public static string HOME_GET_MORE_LIBRARIES_CONTENT {
            get {
                return ResourceManager.GetString("HOME_GET_MORE_LIBRARIES_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        public static string HOME_GETTING_STARTED {
            get {
                return ResourceManager.GetString("HOME_GETTING_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that enables a clean separation of concerns and gives you full control over markup for enjoyable, agile development..
        /// </summary>
        public static string HOME_GETTING_STARTED_CONTENT {
            get {
                return ResourceManager.GetString("HOME_GETTING_STARTED_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HOME_HOME {
            get {
                return ResourceManager.GetString("HOME_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET.
        /// </summary>
        public static string HOME_JMB_ASPNET {
            get {
                return ResourceManager.GetString("HOME_JMB_ASPNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript..
        /// </summary>
        public static string HOME_JMB_CONTEXT {
            get {
                return ResourceManager.GetString("HOME_JMB_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string HOME_LEARN_MORE {
            get {
                return ResourceManager.GetString("HOME_LEARN_MORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Hosting.
        /// </summary>
        public static string HOME_WEB_HOSTING {
            get {
                return ResourceManager.GetString("HOME_WEB_HOSTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can easily find a web hosting company that offers the right mix of features and price for your applications..
        /// </summary>
        public static string HOME_WEB_HOSTING_CONTENT {
            get {
                return ResourceManager.GetString("HOME_WEB_HOSTING_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string NVB_EMPLOYEES {
            get {
                return ResourceManager.GetString("NVB_EMPLOYEES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NVB_HOME {
            get {
                return ResourceManager.GetString("NVB_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string NVB_LOGIN {
            get {
                return ResourceManager.GetString("NVB_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Directory.
        /// </summary>
        public static string NVB_PROJECT_NAME {
            get {
                return ResourceManager.GetString("NVB_PROJECT_NAME", resourceCulture);
            }
        }
    }
}
